### ISSUE TITLE
Replace enzyme with react-testing-library

### ISSUE THREAD

**Issue by darekkay** [darekkay/dashboard#9]
[React Testing Library](https://testing-library.com/docs/react-testing-library/intro) encourages better, user-centered tests instead of the [Enzyme](https://github.com/enzymejs/enzyme) way to test implementation details.

I've introduced a few tests using react-testing-library already, especially for custom hooks (which Enzyme doesn't handle well).

## Subtasks

- [x] Rewrite all enzyme tests with react-testing-library
- [x] Remove enzyme
- [x] Improve test coverage by writing more (useful) tests
- [x] Include [eslint-plugin-testing-library](https://github.com/testing-library/eslint-plugin-testing-library)
- [x] Fix all [act warnings](https://kentcdodds.com/blog/fix-the-not-wrapped-in-act-warning) (probably solved automatically by removing enzyme tests)

## Resources:

- [Spectrum Community](https://spectrum.chat/testing-library/help-react?tab=posts)
- [9 React Testing Library tips and tricks](https://medium.com/better-programming/9-react-testing-library-tips-and-tricks-5cce3e458282)

**Comment by darekkay** [comment]
It's done 😊
